### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by joshday** [joshday/AverageShiftedHistograms.jl#4]
- [x] fit methods (for both `UnivariateASH` and `BivariateASH` where user doesn't need to provide Range values.  Extend the range of the data and pick a "reasonable" bin width.
- [ ] `pdf(o, x, y)` method for `BivariateASH`
- [ ] `cov(o::BivariateASH)`.  Approximate covariance.
- [x] plot methods.  Figure out best practice for loading plotting packages (Gadfly, etc.) and plot methods without having them as dependency
- [x] docs.  A detailed README is probably sufficient.

**Comment by joshday** [comment]
Checking off plot methods for now, thanks to UnicodePlots and a new show method.

**Comment by Evizero** [comment]
Hi! saw your ANN in the stats mailing list and came to check it out. Cool stuff! Also, it was nice to see someone already using my plotting package! Note that I am already working on the better automatic plotting ranges and manual overwrites, which seem like things that you'd need.

**Comment by joshday** [comment]
Hi!  The terminal plotting makes it nice and easy to play around with the smoothing parameter and kernel, so thanks for UnicodePlots!  I'll keep my eye open for updates.

**Comment by Evizero** [comment]
Automatic plotting range should now be improved (in UnicodePlots master). As soon as I tag the version it should automatically look like that, which I think looks a lot better. 

![axis_improv](https://cloud.githubusercontent.com/assets/10854026/9446293/23c4e9b6-4a91-11e5-8444-c514ee0902a0.png)

options for `xlim` and `ylim` are also implemented now. I'll tag the update soon

**Comment by joshday** [comment]
:+1: Thanks for the heads up.  Looks nice.
